Add snmptrap sidecar
librenms/docker pull request #169
Opened 2021-03-04 12:49 UTC by Zoruk

Fixed #26 
Same as #133 with additional fix

2021-03-14 22:54 UTC, crazy-max requested changes

2021-03-14 22:54 UTC, crazy-max commented on Dockerfile
> +  MIBDIRS="/opt/librenms/mibs:/opt/librenms/mibs/cisco" \
I think `MIBDIRS` should be outsourced from the Dockerfile and placed in your `08-svc-snmptrapd.sh`. We should also allow users to provide their own MIBs. `/data/mibs` could be a good place for this.

2021-03-14 22:54 UTC, crazy-max commented on Dockerfile
> +  MIBDIRS="/opt/librenms/mibs:/opt/librenms/mibs/cisco" \
Also maybe allow additional dirs with an env var like `ADDITIONAL_MIBS` and append them to `MIBDIRS`.

2021-05-20 13:51 UTC, dkmcgowan commented
Look forward to this getting merged in and saving me the time to figure it out, been wanting to add snmp traps to my setup using docker

2021-08-01 05:26 UTC, crazy-max commented
Closed by #180

2021-08-01 05:26 UTC, closed without merging