SNMPTRAPD: misspelling of variable causing the container not to run when correct spelling is used in envournment
librenms/docker pull request #220
Opened 2021-08-09 14:35 UTC by MarlinMr

Problem was introduced in by #180. 

`SIDECAR_SNNMPTRAPD` was spelled with 2 `N`s. This request changes it to the correct 1 `N`. 

This is probably the actual cause for #218 that was "fixed" by #219. The typo will cause the setup not to run, should correct spelling be used by people running it.

Because the spelling error was also put into all documentation, it is possible that people are running the container with the error, and this merge will break it. I suspect @glance- was running it with the error.

2021-08-09 14:43 UTC, crazy-max requested changes
Rebase your branch, thx.

2021-08-10 00:05 UTC, murrant approved these changes

2021-08-10 11:05 UTC, MarlinMr commented
> Rebase your branch, thx.

I think I fixed it

2021-08-10 11:22 UTC, crazy-max approved these changes
LGTM

2021-08-10 11:23 UTC, merged